### ISSUE TITLE
pdf / ppt corruption on Ubuntu

### ISSUE THREAD

**Issue by jethar** [rddill-IBM/ZeroToBlockchain#20]
The fonts are not showing properly on the pdf in Ubuntu. Also pptx is showing as correupt when trying to open with LibreOffice. Is there a specific font on system which is required to view the pdf and ppt documentation files.

**Comment by rddill-IBM** [comment]
thanks for your question. The default ubuntu installation does not include the fonts in this presentation. Please take the following two steps in your Ubuntu OS
(1) Open a Terminal window and execute the following command, accepting the license agreement when prompted: 
```sudo apt-get install ubuntu-restricted-extras```
(2) restart your Ubuntu image, which will activate the newly installed fonts.

**Comment by jethar** [comment]
Thanks for the quick reply. I just did a quick check and actually have this packages already installed - ubuntu-restricted-extras.

Is there anyother font which is needed.
