### ISSUE TITLE
Answers-Documentation

### ISSUE THREAD

**Issue by hckim16** [rddill-IBM/ZeroToBlockchain#22]
Hello,
This is not an issue but a question regarding the "answers" documentation.  It looks like the code there is the same as the code in the working files which is very different than the code you are referencing on your presentation.  You mentioned copying and pasting answers to the working files. But the answer file seems the same as the working files (currently bouncing back and forth between ch. 5 and ch. 6).
Thank you.

**Comment by Limcooo** [comment]
Hi! Yeah some parts seem to be pretty the same. Bob can bring some light to this discussion? Thx I advance!

**Comment by rddill-IBM** [comment]
I will review. Ch4 thru Ch12 should have different content. Probably one too many updates. Thanks and I'll update and post a new release. Will close this issue when that's done.

**Comment by Limcooo** [comment]
Yesterday I was working with Chapter05. After buildAndDeploy and node index. Everything was set correctly. However, when I tried to run environment in browser I was getting something like this: 

```
TypeError: Cannot read property 'getConnectivityState' of undefined
    at ClientDuplexStream.<anonymous> (/opt/share/hyperledger/node_modules/fabric-client/lib/EventHub.js:355:56)
    at emitOne (events.js:116:13)
    at ClientDuplexStream.emit (events.js:211:7)
    at ClientDuplexStream._emitStatusIfDone (/opt/share/hyperledger/node_modules/grpc/src/client.js:236:12)
    at ClientDuplexStream._readsDone (/opt/share/hyperledger/node_modules/grpc/src/client.js:201:8)
    at /opt/share/hyperledger/node_modules/grpc/src/client_interceptors.js:705:15
```

After a few minutes of Googling I was able to fix it with commenting this on row 309 if I am not mistaken.

```
<br/>
<i>         var state = -1;<br/>
            //if(self._stream) state = self._stream.call.channel_.getConnectivityState();<br/>
            logger.debug('on.data - grpc stream state :%s',state);<br/>
</i><br/><br/>
```

It seems it is a known error, which occurred few days ago.

**Comment by rddill-IBM** [comment]
Files in Chapters 4, 5 & 8 were updated to show where work is required. All other chapters were already correct with respect to identifying where work is required. 

Please be aware that this tutorial is based on Hyperledger Composer V0.16 and Hyperledger Fabric V1.01. The error your getting is, I think, related to Fabric V1.1  The tutorial will be updated to Fabric V1.1 when Composer hits release V1.0
