### ISSUE TITLE
startup.sh file missing

### ISSUE THREAD

**Issue by CalvitoUy** [rddill-IBM/ZeroToBlockchain#25]
Hi i make the install following the step-by-step video and readme file and when I run ./buildAndDeploy.sh get this message, (using Ubuntu LTS 16.04 runing on VirtuaBox)

> ./startup.sh: line 37: ./startFabric.sh: No such file or directory
>        =====================================================
>        -----> creating new PeerAdmin card (required with each restart)
>        =====================================================
> ./startup.sh: line 44: ./createPeerAdminCard.sh: No such file or directory

after that a lot of errors is showing in the process, like:

> Installing runtime for business network zerotoblockchain-network. This may take a minute...
> Error: Error trying install composer runtime. Error: No valid responses from any peers.
> Response from attempted peer comms was an error: Error: Connect Failed

or:

> Starting business network definition. This may take a minute...
> Error: Error trying to instantiate composer runtime. Error: Error: SERVICE_UNAVAILABLE
> Command failed

and so on, any cloud about what is going on?
thanks in advance.

**Comment by Limcooo** [comment]
I think I am having the same problem but on Mac OS X

**Comment by rddill-IBM** [comment]
The presence of these errors indicates that the setup_OSX.sh script was not run successfully. Specifically, it is telling me that the composer command line interface was not installed. I would recommend that you open a terminal window in OSX and change to the "ZeroToBlockchain" folder and then run the following command: 
```
./setup_OSX.sh -g false 
```
this will run a complete installation except for installing github desktop. Let me know if you have any errors. If you do, then we'll need to clean up your system and rerun the installation script.

**Comment by CalvitoUy** [comment]
Bob my problem is on Ubuntu virtual machine, i test this a few times even re-install the Ubuntu Desktop and follow the step-by-step and always have the same result "./startup.sh: line 37: ./startFabric.sh: No such file or directory" in effect the startFabric.sh file is not there.
Do you have any idea whats is go in on?

**Comment by rddill-IBM** [comment]
There was a github repo change for hyperledger fabric which I just caught a few days ago. The set up files for OSX and Ubuntu have  been updated to resolve this change and should now work. I expect that the setup_Ubuntu_Part_2.sh script failed during execution and this is the source of your error. 

Please execute the following commands: 
(1) ```curl -H 'Accept: application/vnd.github.v3.raw' https://raw.githubusercontent.com/rddill-IBM/ZeroToBlockchain/master/setup_Ubuntu_Part_2.sh | bash```
(2) If you used the github clone process to get a copy of the tutorial, execute the following commands: 
```
git remote add upstream https://github.com/rddill-IBM/ZeroToBlockchain.git
git pull upstream master
```
(3) If you did not use the clone command to create your repository, please delete it and follow the Chapter 3 instructions for forking and cloning your repository. If, in this process, you discover that you have already forked a copy of the repo, then clone it, and execute the 2 preceding commands.
