### ISSUE TITLE
Provider in Chapter 08

### ISSUE THREAD

**Issue by HuyHoang2017** [rddill-IBM/ZeroToBlockchain#31]
Dear Mr @rddill-IBM 
I order from Seller to Provider. However, In Provider does not have BacktoOrder or Shipping like in YouTube Sir.
![image](https://user-images.githubusercontent.com/34642653/39913067-db6db2ea-552a-11e8-9e87-d232c663ead2.png)

**Comment by diegoduncan21** [comment]
Hi, that ui is from the financer, i think that the financer dont have the option to backtoOrder. The financer just pay after user authorize the payment. The shipper have the options that you are looking for.

**Comment by rddill-IBM** [comment]
Your comments are correct. The only role which can issue a backorder or a shipping request is the Provider and that capability is created in the z2b_shipper.js file in the switch/case statement.
