### ISSUE TITLE
Finance 

### ISSUE THREAD

**Issue by HuyHoang2017** [rddill-IBM/ZeroToBlockchain#32]
Dear Mr @rddill-IBM,
The Buyer has approved payment, but In Finance Company User Experience function, I can not set Pay in Finance. Could you show me how to fix? Thank you so much
![image](https://user-images.githubusercontent.com/34642653/40040960-93abd508-5846-11e8-85ed-521fc39ba7a2.png)

![image](https://user-images.githubusercontent.com/34642653/40040904-4d7c5e86-5846-11e8-8fb9-27a093f4107c.png)

**Comment by rddill-IBM** [comment]
Then it would appear that you are missing code in the switch/case statement in the z2b-finance.js file. This is located in the formatFinanceOrders function starting at line 81 in the original file.
