### ISSUE TITLE
Chapter 6 card not found

### ISSUE THREAD

**Issue by Furmy** [rddill-IBM/ZeroToBlockchain#37]
Hi,

I have met with below issue and I don't know how to fix this issue. Can you help me please?

[13] at: 10:54:39.923 Url is: /composer/client/getMyOrders
getMyOrders req.body.userID is: yes@softwaresolutionsinc.com
getMyOrders req.body.userID is: yes@softwaresolutionsinc.com
businessNetwork connect failed  { Error: Card not found: yes@softwaresolutionsinc.com
    at store.get.then.catch (/Users/userm/Blockchain/ZeroToBlockchain/Chapter06/node_modules/composer-common/lib/cardstore/walletbackedcardstore.js:74:27)
    at <anonymous>
  cause: 
   { Error: ENOENT: no such file or directory, stat '/Users/userm/.composer/cards/yes@softwaresolutionsinc.com'
     errno: -2,
     code: 'ENOENT',
     syscall: 'stat',
     path: '/Users/userm/.composer/cards/yes@softwaresolutionsinc.com' } }

This issue occur by method geMyOrders(Display Order Status), well also by creating order.
I know that it doesn't work because there is no user card in the wallet. Is there any script that creating also users card, that I could miss somehow or any other solution?

Thank you for your answer.

**Comment by rddill-IBM** [comment]
It appears that the autoLoad option when executed had errors. I would do the following: 
(1) run buildAndDeploy ...This will recreate a new business network based on your current model definitions
(2) after running npm start and accessing your application, select the 'autoLoad' option from the Admin pull-down menu. 

Let me know if there are any errors running either of the preceding commands.
