### ISSUE TITLE
Chapter 13 - Autoload Not Initiating

### ISSUE THREAD

**Issue by ChiragETRM** [rddill-IBM/ZeroToBlockchain#42]
On clicking pre-load the network on the broweser, it says Autoload Initiated. However, no blocks are created even after waiting for 20mins.

**Comment by rddill-IBM** [comment]
1. What chapter are you working on? 
2. Do you see any errors in your terminal window? 
3. Do you see any errors in your Browser Console? 
4. Did you update all of the code in the HTML, JS and controller folders?
