### ISSUE TITLE
Debian stretch not supported 

### ISSUE THREAD

**Issue by sonfack** [rddill-IBM/ZeroToBlockchain#43]
Unable to install development environment on Debian 9 (stretch)
curl -H 'Accept: application/vnd.github.v3.raw' https://raw.githubusercontent.com/rddill-IBM/ZeroToBlockchain/master/setup_Ubuntu_Part_2.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6481  100  6481    0     0  12270      0 --:--:-- --:--:-- --:--:-- 12297
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.5 (stretch)
Release:	9.5
Codename:	stretch
No LSB modules are available.
Error: Ubuntu stretch is not supported

**Comment by rddill-IBM** [comment]
HyperLedger Composer is only supported on Ubuntu LTS (16 and 18) and OSX. There is no announced support from the Hyperledger Community for Debian or other operating systems.
