### ISSUE TITLE
some npm packages deprecated when installing for linux due to new verions or not maintained packages 

### ISSUE THREAD

**Issue by Mtea994** [rddill-IBM/ZeroToBlockchain#46]
when installing for linux using the curl commands npm warns about some deprecated versions of some packages is it okay to keep it that way or should i install the updated versions 
![image](https://user-images.githubusercontent.com/20420633/48667109-095e6800-eaf1-11e8-919e-f9342959ac34.png)

**Comment by rddill-IBM** [comment]
It's ok to continue.
