### ISSUE TITLE
File name has wrong extension in Chapter 6 code

### ISSUE THREAD

**Issue by dwakeman** [rddill-IBM/ZeroToBlockchain#5]
The chapter 6 code fails when you try to click on the "get order status" button.  This line of code:

https://github.com/rddill-IBM/ZeroToBlockchain/blob/bbe80b5f7af031de985bc5782d15c0255909d69a/Chapter06/controller/restapi/features/composer/hlcClient.js#L212

references a file name of `memberList.txt` but the actual file name is `memberList.json`, so that line fails.   I'm not sure if the answer is to just change the extension, but that did seem to fix the failure.  However On line 95:
https://github.com/rddill-IBM/ZeroToBlockchain/blob/bbe80b5f7af031de985bc5782d15c0255909d69a/Chapter06/controller/restapi/features/composer/hlcClient.js#L95

there is a reference to a file called `itemList.txt` that is not present in the `startup` directory.

Also, there is a reference to memberList.txt in the `autoload.js` script.  I changed the extension, but now I get an identity error when connecting to the business network when I click the `Get Order Status` button for the user `yes@softwaresolutionsinc.com`.

**Comment by rddill-IBM** [comment]
no, actually, those are 3 different files. you may recall from the video that, before I start using the Buyer interface, I go to the Admin option and select "AutoLoad", which loads up buyer, seller, shipper, provider and finance members, along with 9 orders. The memberList.txt and the itemList.txt files are created when the autoLoad exec is run. This needs to be done each time the application starts, after running the buildAndDeploy script.
