### ISSUE TITLE
bash: ./buildAndDeploy.sh: No such file or directory

### ISSUE THREAD

**Issue by akshaykulkarni1205** [rddill-IBM/ZeroToBlockchain#56]
I on Chapter04 of ZeroToBlockchain and while executing the command: ./buildAndDeploy.sh I am facing the following error : **bash: ./buildAndDeploy.sh: No such file or directory**

Earlier I did try this for Chapter03, and it ran successfully. However today I am getting this error for Chapter 04. I tried it again for Chapter03 and the same error.

I am using ubuntu for this (not VM). 

Please help!.

**Comment by akshaykulkarni1205** [comment]
I am now getting this error for Chapter03 as well. Tried everything from Issue (https://github.com/rddill-IBM/ZeroToBlockchain/issues/1) however nothing is working. 

I dont understand what is happening, Please help.

**Comment by rddill-IBM** [comment]
Drop the .sh from the command. It’s just ./buildAndDeploy

**Comment by akshaykulkarni1205** [comment]
Thank You Bob. That worked!.
