### ISSUE TITLE
npm test error Chapter 04

### ISSUE THREAD

**Issue by akshaykulkarni1205** [rddill-IBM/ZeroToBlockchain#57]
After I run the command npm test I do not  get the results as shown in the video. I am getting Test Failed. But localhost is giving the required interface.

**Comment by rddill-IBM** [comment]
The error is due to a missing empty line at the end of the license information in the only JavaScript file in the Documentation/answers/lib folder

**Comment by akshaykulkarni1205** [comment]
So that isnt a problem?
