### ISSUE TITLE
Chap 05 - node index command error

### ISSUE THREAD

**Issue by mlecjm** [rddill-IBM/ZeroToBlockchain#8]
Hello,
I am learning about Hyperledger technology through the ZeroToBlockchain online course. 
By following the demo video, from the Chapter05 after running "./buildAndDeploy" command which has run successfully. However I got an error message after running "node index" from the terminal to start the node.js server.  Could you help me to fix this issue ?
Please find in the attached file the error message mentioned earlier.

![image](https://user-images.githubusercontent.com/20576517/33417212-e4141e32-d5e3-11e7-8887-5469bbd322bd.png)

**Comment by mir-nawaz** [comment]
Please run . 
npm install 
In chapter05 folder

**Comment by mlecjm** [comment]
Thank you for your support.
I am really enjoying the course.

**Comment by rddill-IBM** [comment]
that's correct, you need to run npm install before you can successfully run node index.

**Comment by akshaykulkarni1205** [comment]
I tried running npm install, but no success
